name: PlayerBiomes
main: com.pseudosmp.PlayerBiomes.PlayerBiomes
version: 1.0.0
description: Plugin for Getting player biome using NMS through a PlaceholderAPI placeholder
api-version: "1.13"
depend:
  - PlaceholderAPI
